<a href="https://colab.research.google.com/github/brijeshchoudhury99/Basic-Machine-Learning-Codes/blob/master/Matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

R1 = int(input("Enter the number of rows for 1st matrix:"))
C1 = int(input("Enter the number of columns for 1st matrix:"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
matrix1 = np.array(entries).reshape(R1, C1)

R2 = int(input("Enter the number of rows for 2nd matrix:"))
C2 = int(input("Enter the number of columns for 2nd matrix:"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
matrix2 = np.array(entries).reshape(R2, C2)

print(matrix1)
print(matrix2)

p = len(matrix1)
q = len(matrix1[0])

t = len(matrix2)
r = len(matrix2[0])
if(q!=t):
   print("Error! Matrix sizes are not compatible")
   quit()

C = []
for row in range(p):
   curr_row = []
   for col in range(r):
       curr_row.append(0)
   C.append(curr_row)

for i in range(p):
   for j in range(r):
       curr_val = 0
       for k in range(q):
           curr_val += matrix1[i][k]*matrix2[k][j]
       C[i][j] = curr_val

print(C)

Enter the number of rows for 1st matrix:3
Enter the number of columns for 1st matrix:2
Enter the entries in a single line (separated by space): 
1 2 3 4 5 6
Enter the number of rows for 2nd matrix:2
Enter the number of columns for 2nd matrix:3
Enter the entries in a single line (separated by space): 
6 5 4 3 2 1
[[1 2]
 [3 4]
 [5 6]]
[[6 5 4]
 [3 2 1]]
[[12, 9, 6], [30, 23, 16], [48, 37, 26]]
