<a href="https://colab.research.google.com/github/brijeshchoudhury99/Basic-Machine-Learning-Codes/blob/master/Matrix_Addition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

R1 = int(input("Enter the number of rows for 1st matrix:"))
C1 = int(input("Enter the number of columns for 1st matrix:"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
matrix1 = np.array(entries).reshape(R1, C1)

R2 = int(input("Enter the number of rows for 2nd matrix:"))
C2 = int(input("Enter the number of columns for 2nd matrix:"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
matrix2 = np.array(entries).reshape(R2, C2)

print(matrix1)
print(matrix2)

p = len(matrix1)
q = len(matrix1[0])

t = len(matrix2)
r = len(matrix2[0])
C = []
for row in range(p):
   curr_row = []
   for col in range(r):
       curr_row.append(0)
   C.append(curr_row)

for i in range(p):
   for j in range(r):
       curr_val = 0
       for k in range(q):
           curr_val = matrix1[i][j]+matrix2[i][j]
       C[i][j] = curr_val
print(C)

Enter the number of rows for 1st matrix:4
Enter the number of columns for 1st matrix:5
Enter the entries in a single line (separated by space): 
1 2 3 4 5 6 7  8 9 10 11 12 13 14 15 16 17 18 9 20
Enter the number of rows for 2nd matrix:4
Enter the number of columns for 2nd matrix:5
Enter the entries in a single line (separated by space): 
20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18  9 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[21, 21, 21, 21, 21], [21, 21, 21, 21, 21], [21, 21, 21, 21, 21], [21, 21, 21, 11, 21]]
